### ISSUE TITLE
rewrite unregister enclave

### ISSUE THREAD

**Issue by clangenb** [integritee-network/pallet-teerex#10]
Currently unregister enclave is quite useless, we can't expect to unregister an enclave by itselfs.

We should either rewrite it such that:
* (Bad idea) another enclave can unregister an enclave. Question: When is that the case? If a worker cannot be reached?
* Implement heartbeat in request and unregister automatically if there has been no word from a worker for a long time. Here we could use the timestamp module, which is already used in the registry and use the `OnTimestamp` method to check if there are silent workers.

**Comment by echevrier** [comment]
I'm implementing the 2d idea. What does it mean for long time? Shall it be different for configurable in the node?
What is "for a long time"? 
Can this time be different for different nodes and so configurable?

**Comment by brenzi** [comment]
the way you did it is fine for now
