### ISSUE TITLE
Discriminate production or debug mode for SGX RA in enclave registry

### ISSUE THREAD

**Issue by brenzi** [integritee-network/pallet-teerex#28]
Our teerex registry currently only allows SGX_MODE HW debug.

Goals:
* The pallet should be able to verify both debug mode and production mode
* The enclave registry should store the mode, either production or debug. Maybe the worker needs to specify this when registering the enclave, maybe we can derive it from RA payload directly?
* allow global restriction to one of the two modes for the entire chain

Steps:
* add root CA certificate in ias-verify for production if different (I believe it is different)
* ....

**Comment by brenzi** [comment]
@haerdib may I ask you to further specify this task for @echevrier or add pointers? Some SGX docs research may be needed

**Comment by haerdib** [comment]
I believe @clangenb is the better help here, as I hardly ever worked with the pallet_teerex respective with the attestation itself.
I'm also not sure if the CA certificate differs for production mode, but it is certainly queried from a different source: 
https://github.com/integritee-network/worker/blob/master/enclave-runtime/src/attestation.rs#L64-L74
```rust
pub const DEV_HOSTNAME: &str = "api.trustedservices.intel.com";

#[cfg(feature = "production")]
pub const SIGRL_SUFFIX: &str = "/sgx/attestation/v4/sigrl/";
#[cfg(feature = "production")]
pub const REPORT_SUFFIX: &str = "/sgx/attestation/v4/report";

#[cfg(not(feature = "production"))]
pub const SIGRL_SUFFIX: &str = "/sgx/dev/attestation/v4/sigrl/";
#[cfg(not(feature = "production"))]
pub const REPORT_SUFFIX: &str = "/sgx/dev/attestation/v4/report";
```

**Comment by clangenb** [comment]
I have researched a bit on the remote attestation report.

The build mode is contained in the `SgxReportBody`s [attibute_field](https://github.com/integritee-network/pallet-teerex/blob/fab14a05744034c7a29fd6dc6f4437cb2272a7aa/ias-verify/src/lib.rs#L52) according to the source code of intel's [ra-sample](https://github.com/intel/sgx-ra-sample/blob/876dde79ca58f5f60c4d9dd5b2a6d5e0ef66c5fd/enclave_verify.c#L61).

According to the [attributes.h](https://github.com/intel/linux-sgx/blob/6b8d2d14d0daf8ed421165eb3347e7ee15bbf9d0/common/inc/sgx_attributes.h#L39), it seems to be the second bit of the attributes.

**Comment by clangenb** [comment]
So I suggest following procedure:

* I don't think we need to touch the verification code. We could simply implement a method for the `SgxReportBody` to extract the `SgxBuildMode`from it, where the `SgxBuildMode` is a new enum we introduce. The runtime code should handle, what it wants to allow.
* We add field `sgx_mode` to the `Enclave` struct.
* So the runtime gets back a `SgxReportBody` from the verification and depending on the configuration it either adds the enclave or returns an error like: `SgxModeNotAllowed(SgxBuildMode)`
* Configuration needs to be compiler flag as far as I know. I don't think the runtime has access to the CLI.

**Comment by brenzi** [comment]
we could introduce a module constant ALLOW_SGX_DEBUG_MODE. Don't think a compiler flag is the right approach. arguments?

**Comment by clangenb** [comment]
I want to prevent to touch the code to get different variants. 

I think this is a good situation to introduce a genesis config field, why did I not think about this before??? 

Then we can introduce different chain_specs depending on what we want. This is IMO the best solution.

We should do the same for skip-ias-check, i.e, remove the compiler flag and introduce a genesis config field.

**Comment by brenzi** [comment]
I can agree to doing genesis config for allow_sgx_debug_mode but I don't think we should do the same for skip-ias-check. Reasoning: our registry is effectively worthless without ias check and we only need skip-ra in CI, but never in production.

**Comment by brenzi** [comment]
We are blocked here by
https://github.com/integritee-network/worker/issues/424

But let's not wait. We can add the unit test for production once we have the necessary test data.

**Comment by brenzi** [comment]
@echevrier please submit a PR

**Comment by brenzi** [comment]
I was able to build a production mode worker and added the necessary test data in 1d78c2167f2d6fa1d24a23485208e565db2b1522

@echevrier please finish implementing the respective tests

**Comment by echevrier** [comment]
> I was able to build a production mode worker and added the necessary test data in [1d78c21](https://github.com/integritee-network/pallet-teerex/commit/1d78c2167f2d6fa1d24a23485208e565db2b1522)
> 
> @echevrier please finish implementing the respective tests

@brenzi For the unit test we also need the corresponding timestamp (TEST8_TIMESTAMP) and signer_pub (TEST8_SIGNER_PUB)

**Comment by echevrier** [comment]
> > I was able to build a production mode worker and added the necessary test data in [1d78c21](https://github.com/integritee-network/pallet-teerex/commit/1d78c2167f2d6fa1d24a23485208e565db2b1522)
> > @echevrier please finish implementing the respective tests
> 
> @brenzi For the unit test we also need the corresponding timestamp (TEST8_TIMESTAMP) and signer_pub (TEST8_SIGNER_PUB)
 Sorry, I found them.
